### PR TITLE
add static RV framework figure

### PR DESCRIPTION
**Pull request by saigrain**
Hi Dan, am I doing this right...?

### CODE REVIEW

**Comment by dfm** [comment]
I think so! Let's try merging and see if it ends up in the Overleaf...

**Comment by dfm** [comment]
hmm doesn't seem to be working. I'll debug a little!

**Comment by dfm** [comment]
OK working now! I've added a placeholder for that figure in the RV stellar variability section.

**Comment by saigrain** [comment]
Ok, out of interest what did you have to change?

**Comment by dfm** [comment]
We needed to have the figure environment in the Overleaf document for showyourwork to recognize that it needed to push that file, but the issue I was having was caused by the Overleaf being slow to sync, I think!

**Comment by saigrain** [comment]
Cool! I’m signing off for today. Tomorrow I’ll make another (probably also static) figure for the basic GPR workflow

**Pull request merged**
